import { ArrowUpRight, Compass, HeartHandshake, MoveUpRight } from "lucide-react";
import { Link } from "wouter";

import coach from "@/assets/images/coach.jpg";
import team from "@/assets/images/team.jpg";
import detail from "@/assets/images/detail.jpg";

export default function About() {
 return <>
  <section className="page-hero-v2 bg-cobalt"><div className="container relative z-10"><p className="eyebrow text-lime">02 / Our standard</p><h1 className="page-title-v2 mt-6">Set the<br/><em>line.</em></h1><p className="mt-8 max-w-xl text-lg leading-8 text-white/70">Inspire Goalkeeping is built around a clear standard: make the work simple, make the environment positive and make the player braver.</p></div></section>
  <section className="section-pad bg-cloud"><div className="container grid items-center gap-12 lg:grid-cols-[.85fr_1.15fr] lg:gap-24"><div className="split-image h-[520px]"><img src={coach} alt="Inspire Goalkeeping coach on a training pitch"/><span className="image-label">Coach / player / process</span></div><div><p className="eyebrow text-cobalt">Why Inspire?</p><h2 className="section-title-v2 mt-5">The goalkeeper<br/><em>comes first.</em></h2><p className="mt-7 max-w-xl text-sm leading-7 text-slate-500">The position is demanding enough. Our job is to make the next step clear. We create sessions that blend technical detail, real decisions and the confidence to try again.</p><p className="mt-5 max-w-xl text-sm leading-7 text-slate-500">That means a player-first environment, honest feedback, and a belief that progress is built in the small moments.</p><div className="mt-10 grid gap-5 sm:grid-cols-2"><div className="border-t-2 border-cobalt pt-4"><HeartHandshake className="text-cobalt" size={23}/><p className="mt-5 font-display text-xl font-bold">Positive pressure</p><p className="mt-2 text-sm leading-6 text-slate-500">Challenge the player without losing the joy.</p></div><div className="border-t-2 border-cobalt pt-4"><MoveUpRight className="text-cobalt" size={23}/><p className="mt-5 font-display text-xl font-bold">Always forward</p><p className="mt-2 text-sm leading-6 text-slate-500">Leave every session with a next action.</p></div></div></div></div></section>
  <section className="section-pad bg-white"><div className="container"><div className="grid gap-12 lg:grid-cols-[1fr_.9fr] lg:items-center"><div><p className="eyebrow text-cobalt">The academy idea</p><h2 className="section-title-v2 mt-5">Clear heads.<br/><em>Brave hands.</em></h2><p className="mt-7 max-w-lg text-sm leading-7 text-slate-500">Every goalkeeper deserves a space where the technical side is taken seriously and the human side is never forgotten.</p><Link href="/contact" className="button button-cobalt mt-9">Train with us <ArrowUpRight size={16}/></Link></div><div className="split-image h-[390px]"><img src={detail} alt="Goalkeeper gloves gripping a football beside a goal post"/><span className="image-label">Trust the work</span></div></div></div></section>
  <section className="section-pad bg-fog"><div className="container"><div className="grid gap-8 md:grid-cols-[.8fr_1.2fr] md:items-end"><div><p className="eyebrow text-cobalt">Built in the South-East</p><h2 className="section-title-v2 mt-5">Find your<br/><em>people.</em></h2></div><div className="flex items-end justify-between gap-8"><p className="max-w-sm text-sm leading-7 text-slate-500">For players, families and clubs across the South-East of Ireland who want a sharper goalkeeper environment.</p><Compass className="hidden text-cobalt sm:block" size={55} strokeWidth={1.2}/></div></div><div className="mt-12 grid gap-3 sm:grid-cols-3"><div className="bg-white p-5"><span className="eyebrow text-cobalt">For players</span><p className="mt-12 font-display text-2xl font-bold">Find your next rep.</p></div><div className="bg-lime p-5"><span className="eyebrow text-cobalt">For families</span><p className="mt-12 font-display text-2xl font-bold">See the progress.</p></div><div className="bg-cobalt p-5 text-white"><span className="eyebrow text-lime">For clubs</span><p className="mt-12 font-display text-2xl font-bold">Raise the standard.</p></div></div></div></section>
 </>;
}
