import { ArrowUpRight, Check, Layers3, UserRound, Users } from "lucide-react";
import { Link } from "wouter";

const options = [
  { icon: Users, label: "GROUP TRAINING", title: "Weekly academy", intro: "For keepers who want a consistent place to train, compete and improve.", details: ["All ages and ability levels", "Technical + game-based sessions", "Train with a positive group"], style: "" },
  { icon: UserRound, label: "PERSONALISED", title: "1–2–1 performance", intro: "For players who want a focused plan and clear feedback on their next step.", details: ["Goalkeeper-specific assessment", "Session built around your priority", "Ideal for trials and progression"], style: "cobalt" },
  { icon: Layers3, label: "CLUBS + EVENTS", title: "Clubs, clinics & camps", intro: "For clubs, schools and players who want more high-quality goalkeeper work.", details: ["Specialist club coaching", "Camps and holiday clinics", "High-repetition environments"], style: "lime" },
];

export default function Coaching() {
 return <>
  <section className="page-hero-v2"><div className="container relative z-10"><p className="eyebrow text-lime">01 / The programme</p><h1 className="page-title-v2 mt-6">Train with<br/><em>intent.</em></h1><p className="mt-8 max-w-xl text-lg leading-8 text-white/65">Clear coaching pathways for keepers who want to enjoy the position and get better at it.</p></div></section>
  <section className="section-pad bg-cloud"><div className="container"><div className="grid gap-4 lg:grid-cols-3">{options.map(option => { const Icon = option.icon; const dark = option.style === "cobalt"; return <article key={option.title} className={`pathway-v2 ${option.style}`}><div className="flex items-start justify-between"><div className="pathway-icon-v2"><Icon size={24} strokeWidth={1.8}/></div><span className={`eyebrow ${dark ? "text-lime" : "text-slate-500"}`}>{option.label}</span></div><h2 className="mt-20 max-w-xs font-display text-3xl font-bold leading-[.95] tracking-[-.07em]">{option.title}</h2><p className={`mt-5 max-w-sm text-sm leading-6 ${dark ? "text-white/70" : "text-slate-500"}`}>{option.intro}</p><ul className={`mt-8 space-y-3 border-t pt-6 text-sm ${dark ? "border-white/20 text-white/75" : "border-ink/15 text-slate-600"}`}>{option.details.map(detail => <li key={detail} className="flex items-start gap-2"><Check size={16} className={`mt-0.5 shrink-0 ${dark ? "text-lime" : "text-cobalt"}`}/>{detail}</li>)}</ul><Link href="/contact" className={`text-link mt-8 ${dark ? "text-lime border-lime" : ""}`}>Ask about this <ArrowUpRight size={16}/></Link></article>})}</div></div></section>
  <section className="section-pad bg-white"><div className="container grid gap-12 lg:grid-cols-[.75fr_1.25fr] lg:gap-24"><div><p className="eyebrow text-cobalt">Inside the session</p><h2 className="section-title-v2 mt-5">Four things<br/><em>we chase.</em></h2></div><div className="grid gap-8 sm:grid-cols-2"><div className="border-t-2 border-cobalt pt-4"><span className="font-mono text-xs text-cobalt">01 / MOVE</span><h3 className="mt-8 font-display text-2xl font-bold">Better feet</h3><p className="mt-3 text-sm leading-6 text-slate-500">Set position, footwork and movement patterns that make the next action simpler.</p></div><div className="border-t-2 border-cobalt pt-4"><span className="font-mono text-xs text-cobalt">02 / SEE</span><h3 className="mt-8 font-display text-2xl font-bold">Earlier eyes</h3><p className="mt-3 text-sm leading-6 text-slate-500">Read the picture before the ball arrives and make cleaner decisions.</p></div><div className="border-t-2 border-cobalt pt-4"><span className="font-mono text-xs text-cobalt">03 / ACT</span><h3 className="mt-8 font-display text-2xl font-bold">Brave hands</h3><p className="mt-3 text-sm leading-6 text-slate-500">Handling, diving and claiming with the confidence to commit.</p></div><div className="border-t-2 border-cobalt pt-4"><span className="font-mono text-xs text-cobalt">04 / RESET</span><h3 className="mt-8 font-display text-2xl font-bold">Next action</h3><p className="mt-3 text-sm leading-6 text-slate-500">Mistakes become information. Reset quickly and stay in the game.</p></div></div></div></section>
  <section className="section-pad bg-fog"><div className="container flex flex-col items-start justify-between gap-8 bg-cobalt px-7 py-12 text-white sm:px-12 md:flex-row md:items-end"><div><p className="eyebrow text-lime">Not sure which route?</p><h2 className="mt-4 max-w-xl font-display text-4xl font-bold leading-[.9] tracking-[-.07em] sm:text-5xl">Tell us where the goalkeeper is going.</h2></div><Link href="/contact" className="button button-lime shrink-0">Start a conversation <ArrowUpRight size={16}/></Link></div></section>
 </>;
}
