import { ArrowDownRight, ArrowUpRight, Check, ChevronRight, CircleDot, Crosshair, Gauge, ShieldCheck } from "lucide-react";
import { Link } from "wouter";

import hero from "@/assets/images/hero.jpg";
import drill from "@/assets/images/drill.jpg";
import team from "@/assets/images/team.jpg";
import coach from "@/assets/images/coach.jpg";
import detail from "@/assets/images/detail.jpg";

const services = [
  { no: "01", title: "Weekly academy", text: "A consistent training rhythm for keepers who want to improve every week." },
  { no: "02", title: "1–2–1 performance", text: "A focused plan for the details that unlock the next level." },
  { no: "03", title: "Club goalkeeper", text: "Specialist support for clubs who want better keepers and better sessions." },
  { no: "04", title: "Camps & clinics", text: "Big energy, high repetition and a room full of players who get it." },
];

export default function Home() {
  return <>
    <section className="hero-v2"><img className="hero-photo" src={hero} alt="Goalkeeper catching a high ball on a sunlit football pitch"/><div className="hero-grid"/><div className="container hero-inner"><div className="flex items-start justify-between"><div><span className="hero-kicker">South-East Ireland / since 2023</span><p className="hero-slogan">Let’s Develop the Next Generation of Goalkeepers</p></div><span className="hidden font-mono text-[.62rem] uppercase tracking-[.16em] text-white/55 sm:block">Performance first</span></div><div><h1 className="hero-title">Make the<br/><em>next</em> save<br/>yours.</h1><div className="mt-8 flex flex-col gap-8 sm:flex-row sm:items-end sm:justify-between"><p className="hero-sub">Goalkeeper coaching built for young players who want to move better, think earlier and play with more belief.</p><Link href="/contact" className="button button-lime w-fit">Join the academy <ArrowUpRight size={16}/></Link></div></div><div className="flex flex-col gap-5 border-t border-white/25 pt-5 sm:flex-row sm:items-end sm:justify-between"><a href="#start" className="inline-flex items-center gap-2 font-mono text-[.64rem] uppercase tracking-[.15em] text-white/65">See how we work <ArrowDownRight size={15} className="text-lime"/></a><div className="flex gap-8"><div className="hero-stat"><strong>4</strong><span>ways to<br/>train</span></div><div className="hero-stat"><strong>1</strong><span>keeper-first<br/>standard</span></div></div></div></div></section>
    <div className="marquee-v2"><div className="marquee-track-v2"><span>Own the moment</span><i>✳</i><span>Move with intent</span><i>✳</i><span>Raise your line</span><i>✳</i><span>Own the moment</span><i>✳</i><span>Move with intent</span><i>✳</i></div></div>
    <section id="start" className="section-pad bg-cloud"><div className="container"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:gap-24"><div><p className="eyebrow text-cobalt">A different kind of coaching</p><h2 className="section-title-v2 mt-5">The position<br/><em>demands</em> more.</h2></div><div className="lg:pt-10"><p className="lead-v2 max-w-2xl">We build goalkeepers who are technically ready, mentally brave and clear on what comes next.</p><p className="mt-6 max-w-xl text-sm leading-7 text-slate-500">Inspire Goalkeeping is a specialist academy for boys and girls of all ages and ability levels. Every session has a purpose: better movement, better decisions and more confidence in the next moment.</p><Link href="/about" className="text-link mt-8">Our standard <ArrowUpRight size={16}/></Link></div></div><div className="mt-16 grid gap-4 md:grid-cols-3"><div className="v2-card"><div className="number-badge"><Crosshair size={17}/></div><h3 className="mt-16 font-display text-2xl font-bold tracking-tight">Technique that travels</h3><p className="mt-3 text-sm leading-6 text-slate-500">Skills that hold up when the game speeds up.</p></div><div className="v2-card bg-cobalt text-white"><div className="number-badge bg-lime text-ink"><Gauge size={17}/></div><h3 className="mt-16 font-display text-2xl font-bold tracking-tight">Decisions under pressure</h3><p className="mt-3 text-sm leading-6 text-white/70">Read the picture. Set the line. Own the action.</p></div><div className="v2-card"><div className="number-badge"><ShieldCheck size={17}/></div><h3 className="mt-16 font-display text-2xl font-bold tracking-tight">Confidence to reset</h3><p className="mt-3 text-sm leading-6 text-slate-500">Every mistake is feedback for the next save.</p></div></div></div></section>
    <section className="section-pad bg-white"><div className="container"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="eyebrow text-cobalt">The programme</p><h2 className="section-title-v2 mt-5">Choose your<br/><em>next rep.</em></h2></div><Link href="/coaching" className="text-link mb-2">Explore coaching <ArrowUpRight size={16}/></Link></div><div className="mt-14 service-list-v2">{services.map(item => <Link href="/coaching" key={item.no} className="service-item-v2 group"><span className="font-mono text-xs text-cobalt">{item.no}</span><div><h3>{item.title}</h3><p>{item.text}</p></div><ChevronRight className="service-arrow transition-transform group-hover:translate-x-1" size={21}/></Link>)}</div></div></section>
    <section className="section-pad bg-fog"><div className="container grid items-center gap-12 lg:grid-cols-[1.1fr_.9fr] lg:gap-24"><div className="split-image h-[430px] md:h-[590px]"><img src={drill} alt="Goalkeeper moving through an agility drill"/><span className="image-label">01 / move well</span></div><div><p className="eyebrow text-cobalt">The work is the thing</p><h2 className="section-title-v2 mt-5">Small details.<br/><em>Big difference.</em></h2><p className="mt-7 max-w-md text-sm leading-7 text-slate-500">From set position to distribution, we make the invisible parts of goalkeeping easier to see, feel and repeat.</p><ul className="mt-8 space-y-3 text-sm font-semibold"><li className="flex items-center gap-3"><CircleDot size={15} className="text-cobalt"/> Footwork before the save</li><li className="flex items-center gap-3"><CircleDot size={15} className="text-cobalt"/> Early eyes, clear decisions</li><li className="flex items-center gap-3"><CircleDot size={15} className="text-cobalt"/> Brave hands, calm reset</li></ul><Link href="/coaching" className="button button-cobalt mt-9">See the programme <ArrowUpRight size={16}/></Link></div></div></section>
    <section className="section-pad bg-white"><div className="container"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="eyebrow text-cobalt">The people in it</p><h2 className="section-title-v2 mt-5">Find your<br/><em>team.</em></h2></div><p className="max-w-sm text-sm leading-6 text-slate-500 md:mb-2">A positive place for players to compete, learn and leave training feeling ready for the next one.</p></div><div className="team-strip mt-12"><img src={team} alt="Young goalkeepers standing together after training"/><img src={coach} alt="Goalkeeper coach on a training pitch"/><img src={detail} alt="Goalkeeper gloves holding a football"/></div><div className="mt-10 flex flex-col items-start justify-between gap-5 border-t border-ink/15 pt-6 sm:flex-row sm:items-center"><span className="font-mono text-xs uppercase tracking-[.14em] text-slate-500">Players / families / clubs</span><Link href="/contact" className="button button-lime">Start a conversation <ArrowUpRight size={16}/></Link></div></div></section>
    <section className="quote-v2 section-pad"><div className="container relative z-10 grid gap-10 lg:grid-cols-[.75fr_1.25fr] lg:items-center"><div className="split-image h-[380px] lg:h-[500px]"><img src={coach} alt="Inspire Goalkeeping coach"/><span className="image-label">The Inspire standard</span></div><div><p className="eyebrow text-lime">The belief</p><blockquote className="mt-7 max-w-3xl font-display text-[clamp(2.5rem,5vw,5rem)] font-bold leading-[.92] tracking-[-.08em]">“The next save starts with the next <span className="text-lime">decision.</span>”</blockquote><p className="mt-8 text-sm text-white/60">A goalkeeper-first environment, built around clarity, courage and consistency.</p></div></div></section>
    <section className="section-pad bg-lime"><div className="container flex flex-col justify-between gap-10 md:flex-row md:items-end"><div><p className="eyebrow text-cobalt">Ready?</p><h2 className="mt-5 max-w-3xl font-display text-[clamp(3.5rem,8vw,8rem)] font-bold leading-[.82] tracking-[-.09em] text-ink">Make the<br/><span className="text-cobalt">next save</span><br/>yours.</h2></div><Link href="/contact" className="button button-cobalt w-fit">Join in <ArrowUpRight size={16}/></Link></div></section>
  </>;
}
