import { ArrowUpRight, HeartHandshake, MapPin, MoveUpRight } from "lucide-react";
import { Link } from "wouter";

import coachImage from "@/assets/images/coach.jpg";
import saveImage from "@/assets/images/save.jpg";

export default function About() {
  return <>
    <section className="page-hero bg-sand"><div className="container relative z-10"><p className="eyebrow text-coral">The story behind Inspire</p><h1 className="page-title mt-5">Coaching<br /><em>with</em> belief.</h1><p className="mt-8 max-w-xl text-lg leading-8 text-ink/60">Inspire Goalkeeping is a specialist coaching business built around one simple idea: young keepers deserve the tools and belief to enjoy their position.</p></div><div className="page-hero-mark text-ink/10">02</div></section>
    <section className="section-pad bg-paper"><div className="container grid items-center gap-12 lg:grid-cols-[.85fr_1.15fr] lg:gap-24"><div className="image-frame image-frame-portrait"><img src={coachImage} alt="Goalkeeping coach beside a football goal" /><div className="image-caption"><span>Inspire Goalkeeping</span><span>South-East Ireland</span></div></div><div><p className="eyebrow text-coral">Why Inspire?</p><h2 className="section-title mt-5">A specialist<br /><em>voice</em> in the goal.</h2><p className="mt-7 max-w-xl text-base leading-7 text-ink/60">The goalkeeper’s role is different. The coaching should be too. Inspire creates focused, positive sessions that make technical detail feel clear, give players permission to make mistakes and turn hard work into visible progress.</p><p className="mt-5 max-w-xl text-base leading-7 text-ink/60">From the first catch to the pressure of a trial, we want every player to understand that their journey is worth investing in.</p><div className="mt-10 grid gap-5 sm:grid-cols-2"><div className="border-t border-ink/15 pt-4"><HeartHandshake className="text-coral" size={24} strokeWidth={1.5} /><p className="mt-4 font-display text-xl font-semibold">Player-first</p><p className="mt-2 text-sm leading-6 text-ink/55">The player in front of us shapes the session.</p></div><div className="border-t border-ink/15 pt-4"><MoveUpRight className="text-coral" size={24} strokeWidth={1.5} /><p className="mt-4 font-display text-xl font-semibold">Always forward</p><p className="mt-2 text-sm leading-6 text-ink/55">Small improvements become big belief.</p></div></div></div></div></section>
    <section className="section-pad bg-ink"><div className="container grid gap-12 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><div><p className="eyebrow text-coral">The belief</p><h2 className="mt-5 max-w-3xl font-display text-[clamp(3rem,6vw,6rem)] font-semibold leading-[.9] tracking-[-.055em] text-white">Every moment<br />is part of<br /><span className="text-coral">the journey.</span></h2></div><div className="image-frame image-frame-square"><img src={saveImage} alt="Young goalkeeper gathering the ball against a goal net" /></div></div></section>
    <section className="section-pad bg-paper"><div className="container grid gap-10 md:grid-cols-3"><div className="md:col-span-2"><p className="eyebrow text-coral">Where we work</p><h2 className="section-title mt-5">Rooted in<br /><em>the South-East.</em></h2></div><div className="flex items-end"><div className="w-full border-l-2 border-coral pl-5"><MapPin size={21} className="text-coral" strokeWidth={1.5} /><p className="mt-4 text-base leading-7 text-ink/65">Sessions and programmes for players, families and clubs across the South-East of Ireland.</p><Link href="/contact" className="text-link mt-5">Find your starting point <ArrowUpRight size={16} /></Link></div></div></div></section>
  </>;
}
