import { ArrowUpRight, Check, Clock3, Users, UserRound } from "lucide-react";
import { Link } from "wouter";

const options = [
  { icon: Users, label: "Group", title: "Weekly goalkeeper sessions", intro: "A weekly place to learn, repeat and grow alongside other keepers.", details: ["All ages and ability levels", "Technical and game-based learning", "Build confidence through repetition"], accent: "bg-teal" },
  { icon: UserRound, label: "Individual", title: "1–2–1 goalkeeper coaching", intro: "Personalised sessions shaped around the player in front of us.", details: ["Clear focus for every session", "Technical detail and feedback", "Ideal for specific goals or trials"], accent: "bg-coral" },
  { icon: Clock3, label: "Club & events", title: "Clubs, clinics & camps", intro: "Specialist goalkeeper support that lifts the whole environment.", details: ["Club goalkeeper coaching", "Clinics and school-holiday camps", "High-energy, high-repetition formats"], accent: "bg-sand" },
];

export default function Coaching() {
  return <>
    <section className="page-hero bg-ink"><div className="container relative z-10"><p className="eyebrow text-coral">Coaching pathways</p><h1 className="page-title mt-5 text-white">A better<br /><em>next</em> step.</h1><p className="mt-8 max-w-xl text-lg leading-8 text-white/65">Different players need different things. Choose the coaching rhythm that fits the goalkeeper, the family and the goal.</p></div><div className="page-hero-mark">GK<br /><span>01</span></div></section>
    <section className="section-pad bg-paper"><div className="container"><div className="grid gap-5 lg:grid-cols-3">{options.map((option) => { const Icon = option.icon; const darkCard = option.accent === "bg-teal"; return <article key={option.title} className={`pathway-card ${option.accent} ${darkCard ? "text-white" : ""}`}><div className="flex items-start justify-between"><div className={`pathway-icon ${darkCard ? "border-white/30 text-white" : ""}`}><Icon size={25} strokeWidth={1.5} /></div><span className={`eyebrow ${darkCard ? "text-white/55" : "text-ink/45"}`}>{option.label}</span></div><h2 className="mt-20 max-w-xs font-display text-3xl font-semibold leading-[.98] tracking-tight">{option.title}</h2><p className={`mt-5 max-w-sm text-sm leading-6 ${darkCard ? "text-white/70" : "text-ink/65"}`}>{option.intro}</p><ul className={`mt-7 space-y-3 border-t pt-6 text-sm ${darkCard ? "border-white/20 text-white/75" : "border-ink/15 text-ink/70"}`}>{option.details.map((detail) => <li key={detail} className="flex items-start gap-2"><Check size={16} className={`mt-0.5 shrink-0 ${darkCard ? "text-coral" : "text-ink/50"}`} />{detail}</li>)}</ul><Link href="/contact" className={`text-link mt-8 ${darkCard ? "border-white/40 text-white hover:border-coral" : ""}`}>Ask about this <ArrowUpRight size={16} /></Link></article> })}</div></div></section>
    <section className="section-pad bg-sand"><div className="container grid gap-12 lg:grid-cols-[.75fr_1.25fr] lg:gap-24"><div><p className="eyebrow text-coral">A session at Inspire</p><h2 className="section-title mt-5">The detail<br /><em>makes</em> the difference.</h2></div><div className="grid gap-8 sm:grid-cols-2"><div><span className="font-mono text-sm text-coral">01 /</span><h3 className="mt-4 font-display text-2xl font-semibold">Move well</h3><p className="mt-3 text-sm leading-6 text-ink/60">Footwork, set position, handling and movement patterns that make the next action simpler.</p></div><div><span className="font-mono text-sm text-coral">02 /</span><h3 className="mt-4 font-display text-2xl font-semibold">Think early</h3><p className="mt-3 text-sm leading-6 text-ink/60">Decision-making, communication and reading the game before the ball arrives.</p></div><div><span className="font-mono text-sm text-coral">03 /</span><h3 className="mt-4 font-display text-2xl font-semibold">Try again</h3><p className="mt-3 text-sm leading-6 text-ink/60">The confidence to reset, learn from the moment and step back into the next one.</p></div><div><span className="font-mono text-sm text-coral">04 /</span><h3 className="mt-4 font-display text-2xl font-semibold">Enjoy it</h3><p className="mt-3 text-sm leading-6 text-ink/60">Because the best development happens when players feel challenged, supported and excited to return.</p></div></div></div></section>
    <section className="section-pad bg-paper"><div className="container flex flex-col items-start justify-between gap-8 rounded-[2rem] bg-teal px-7 py-12 sm:px-12 md:flex-row md:items-end md:py-16"><div><p className="eyebrow text-coral">Not sure where to start?</p><h2 className="mt-4 max-w-xl font-display text-4xl font-semibold leading-[.95] tracking-tight text-white sm:text-5xl">Tell us about the goalkeeper.</h2></div><Link href="/contact" className="button button-coral shrink-0">Start a conversation <ArrowUpRight size={16} /></Link></div></section>
  </>;
}
