/* ===========================================================================
   CUSTOMER SITE PUBLISHING
   ---------------------------------------------------------------------------
   Web99 now serves finished customer demos directly from Postgres on the AWS
   server at /demo/<slug>. GitHub is NOT part of the customer build path.

   This module keeps the old pushSite() interface so the rest of the pipeline
   remains backwards-compatible while publishing is intentionally local. The
   returned marker is only version metadata; no network request is performed.
   =========================================================================== */

import { W99_START, W99_END } from "./prompts/generator";

export const PUBLISH_PENDING_PREFIX = "pending:github:";

/** Legacy compatibility. New AWS-local builds never return a pending marker. */
export function isPublishPending(value: string | null | undefined): boolean {
  return Boolean(value?.startsWith(PUBLISH_PENDING_PREFIX));
}

/**
 * Finished site files are already persisted in orders.generated by the master
 * pipeline and served by /demo/<slug>. No GitHub token, repo or external
 * deployment is required for a customer preview to exist.
 */
export async function pushSite(
  slug: string,
  _files: Record<string, string>,
  _businessName: string
): Promise<string> {
  return `aws-db:${slug}:${Date.now().toString(36)}`;
}

/**
 * Strip the preview banner and buy buttons once they've paid.
 * Deletes only the fenced Web99 preview furniture.
 */
export function removePreviewFurniture(html: string): string {
  const fenced = new RegExp(
    `${escapeRe(W99_START)}[\\s\\S]*?${escapeRe(W99_END)}\\s*`,
    "g"
  );
  return html.replace(fenced, "");
}

function escapeRe(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
