/* ===========================================================================
   AUTO-GENERATED by scripts/setup-addon-links.ts. Do not hand-edit — rerun
   `npm run setup:addon-links` (with STRIPE_SECRET_KEY set) instead, and it
   will overwrite this file with the current Product/Price/Payment Link IDs.

   Payment Link URLs are public — a customer clicks one to pay — so this file
   is safe to commit. Nothing in it is a secret.
   =========================================================================== */

export interface GeneratedPaymentLink {
  productId: string;
  priceId: string;
  paymentLinkId: string;
  url: string;
}

/* Empty until the setup script has been run once with real Stripe
   credentials. lib/payment-links.ts throws a clear error if something tries
   to use a key that isn't here yet, rather than failing silently. */
export const GENERATED_PAYMENT_LINKS: Record<string, GeneratedPaymentLink> = {};
