/* Every trade the photo library covers. `existing` trades already have images in public/library
   (they only get aliases); the rest are fetched by library-fetch.mjs from Unsplash.
   `q` is the Unsplash search phrase (scene/setting, no people-as-subject); `q2` a close-up of the work.
   `aliases` are the words an owner is likely to use — they drive which folder the model is offered. */

export const existing = {
  plumber: ["plumbing", "boiler", "heating engineer", "drain", "leak", "bathroom fitter"],
  builder: ["construction", "building contractor", "extension", "renovation", "groundworks", "bricklayer", "general builder"],
  "hair-salon": ["hairdresser", "hair stylist", "colourist", "blow dry"],
  cafe: ["coffee shop", "café", "coffee", "brunch"],
  signage: ["sign maker", "signs", "vehicle wraps", "printing", "banners"],
  cleaner: ["cleaning", "domestic cleaning", "house cleaning", "office cleaning", "maid", "deep clean"],
  electrician: ["electrical", "wiring", "rewire", "fuse board", "ev charger"],
  barber: ["barbershop", "gents haircut", "beard trim", "fade"],
  "nail-beauty": ["nails", "beauty salon", "beautician", "lashes", "brows", "manicure", "facial"],
  florist: ["flowers", "bouquet", "wedding flowers"],
  "dental-clinic": ["dentist", "dental", "orthodontist", "teeth whitening"],
  physio: ["physiotherapy", "physiotherapist", "sports injury", "rehab"],
  gym: ["fitness", "personal trainer", "crossfit", "boxing gym"],
  garage: ["mechanic", "car repair", "motor", "nct", "car service", "tyres", "mobile tyres"],
  landscaper: ["landscaping", "gardener", "garden design", "lawn", "hedge", "patio"],
  "painter-decorator": ["painter", "decorator", "painting and decorating", "wallpaper"],
  roofer: ["roofing", "roof repair", "gutters", "slate", "fascia", "soffit"],
  locksmith: ["locks", "lockout", "key cutting", "lock change"],
  accountant: ["accounting", "bookkeeping", "tax return", "payroll", "bookkeeper"],
  solicitor: ["legal", "law firm", "conveyancing", "lawyer", "probate", "will writing"],
  photographer: ["photography", "wedding photographer", "portrait", "photo studio"],
  restaurant: ["bistro", "fine dining", "pizzeria", "gastropub"],
  bakery: ["baker", "cakes", "patisserie", "bread", "cupcakes"],
  boutique: ["clothing", "fashion", "clothes shop", "shoe shop"],
  "pet-groomer": ["dog grooming", "groomer", "pet grooming"],
  removals: ["removal", "man and van", "house move", "storage"],
  flooring: ["floor fitting", "carpets", "laminate", "wooden floors", "vinyl flooring"],
  "car-valeting": ["valeting", "car wash", "car detailing", "mobile valet"],
  carpenter: ["carpentry", "joiner", "joinery", "cabinet maker", "fitted wardrobes", "kitchens"],
  "spa-wellness": ["spa", "massage", "wellness", "sauna", "day spa"],
  "events-wedding": ["wedding", "events", "event planner", "wedding venue", "dj", "marquee"],
};

const t = (key, label, aliases, q, q2) => ({ key, label, aliases, q, q2 });

export const newTrades = [
  /* home & property */
  t("pest-control", "Pest control", ["pest", "rodent", "rats", "mice", "exterminator", "wasp", "bed bugs", "fumigation"], "clean kitchen home interior bright", "pest control technician spraying"),
  t("tiler", "Tiler", ["tiling", "tiles", "wall tiles", "floor tiles", "splashback"], "tiled bathroom modern interior", "tiler laying tiles trowel"),
  t("plasterer", "Plasterer", ["plastering", "skim", "render", "dry lining", "plaster"], "freshly plastered wall room", "plasterer trowel wall"),
  t("windows-doors", "Windows & doors", ["double glazing", "windows", "doors", "glazier", "conservatory", "upvc"], "modern house windows front door", "window frame installation glazing"),
  t("fencing-driveways", "Fencing & driveways", ["fencing", "fence", "driveway", "paving", "gates", "block paving"], "block paved driveway house", "wooden fence panels garden"),
  t("tree-surgeon", "Tree surgeon", ["tree surgery", "tree removal", "arborist", "stump grinding", "tree felling"], "large tree garden woodland", "arborist chainsaw climbing tree"),
  t("window-cleaner", "Window & gutter cleaning", ["window cleaning", "gutter cleaning", "pressure washing", "power washing", "jet wash"], "clean glass windows house exterior", "window cleaner squeegee"),
  t("carpet-cleaning", "Carpet & upholstery cleaning", ["carpet cleaning", "upholstery", "steam cleaning", "sofa cleaning", "rug"], "clean living room carpet sofa", "carpet cleaning machine"),
  t("hvac", "Heating & air conditioning", ["air conditioning", "heat pump", "hvac", "underfloor heating", "radiators", "boiler service"], "modern radiator warm living room", "heat pump outdoor unit installation"),
  t("solar-energy", "Solar & energy", ["solar", "solar panels", "pv", "battery storage", "renewable", "insulation"], "solar panels house roof blue sky", "installer solar panel roof"),
  t("security-systems", "Security & alarms", ["alarm", "cctv", "security camera", "burglar alarm", "smart home", "intercom"], "modern house entrance evening lighting", "cctv camera mounted wall"),
  t("handyman", "Handyman", ["odd jobs", "handyman", "flat pack", "small repairs", "maintenance"], "tidy workshop tools wall organised", "handyman drill fixing shelf"),
  t("kitchen-bathroom-fitter", "Kitchen & bathroom fitter", ["kitchen fitter", "bathroom fitter", "fitted kitchen", "wet room", "worktops"], "modern kitchen island natural light", "fitting kitchen cabinet worktop"),
  t("interior-designer", "Interior designer", ["interior design", "home staging", "styling", "furnishing", "curtains", "blinds"], "styled living room interior warm light", "fabric swatches mood board interior"),
  t("stonemason", "Stonemason & masonry", ["stonework", "masonry", "stone wall", "pointing", "granite", "headstones"], "dry stone wall countryside", "stonemason chisel stone"),
  t("swimming-pool-hot-tub", "Pools & hot tubs", ["swimming pool", "hot tub", "jacuzzi", "pool maintenance", "spa pool"], "hot tub garden evening", "pool water tiles blue detail"),
  t("skip-waste", "Skip hire & waste", ["skip hire", "waste removal", "rubbish removal", "junk", "clearance", "recycling"], "skip container construction site", "house clearance boxes van"),
  t("scaffolding", "Scaffolding", ["scaffold", "scaffolder", "access platform"], "scaffolding house building exterior", "scaffolding poles fittings close"),
  t("welding-metalwork", "Welding & metalwork", ["welder", "welding", "fabrication", "steel", "gates and railings", "blacksmith"], "metal fabrication workshop sparks", "welder torch sparks close up"),
  /* motoring */
  t("car-body-repair", "Car body repair", ["body shop", "dent repair", "smart repair", "spray painting", "panel beating"], "car paint booth workshop", "car body technician sanding panel"),
  t("car-sales", "Car sales", ["used cars", "car dealer", "car dealership", "second hand cars", "motor sales"], "row of cars forecourt sunny", "car keys handover"),
  t("driving-school", "Driving school", ["driving lessons", "driving instructor", "learner driver", "theory test"], "learner car road country", "driving lesson steering wheel hands"),
  t("taxi-transport", "Taxi & transport", ["taxi", "chauffeur", "airport transfer", "minibus", "private hire", "coach hire"], "executive car city street", "chauffeur opening car door"),
  t("courier-delivery", "Courier & delivery", ["courier", "delivery", "parcels", "logistics", "haulage", "van hire"], "delivery van street morning", "parcels boxes stacked delivery"),
  /* health & wellbeing */
  t("chiropractor-osteopath", "Chiropractor & osteopath", ["chiropractor", "osteopath", "back pain", "spine", "sports massage"], "treatment room bright clinic", "spine model treatment hands back"),
  t("massage-therapy", "Massage therapy", ["massage therapist", "holistic", "reflexology", "aromatherapy", "reiki", "acupuncture"], "massage room candles towels", "massage oil stones hands"),
  t("yoga-pilates", "Yoga & pilates", ["yoga", "pilates", "meditation", "mindfulness", "barre", "stretch"], "yoga studio bright wooden floor", "yoga mat detail hands"),
  t("optician", "Optician", ["optician", "eye test", "glasses", "opticians", "eyewear", "contact lenses"], "eyeglasses display shop bright", "eye test equipment optician"),
  t("hearing-clinic", "Hearing clinic", ["hearing aids", "audiologist", "hearing test", "hearing"], "calm clinic consultation room", "hearing aid close up"),
  t("vet", "Veterinary", ["vet", "veterinary", "animal clinic", "pet health", "veterinarian"], "veterinary clinic bright reception", "vet stethoscope dog"),
  t("dog-training-walking", "Dog training & walking", ["dog walker", "dog training", "pet sitter", "kennels", "dog daycare"], "dog walking park trees sunlight", "dog paws lead leash close"),
  t("counselling-therapy", "Counselling & therapy", ["counsellor", "therapist", "psychotherapy", "mental health", "coaching", "life coach"], "calm therapy room armchairs plants", "notebook tea two chairs"),
  t("nutrition", "Nutrition & dietitian", ["dietitian", "nutritionist", "weight loss", "meal plans", "healthy eating"], "fresh vegetables kitchen table light", "chopping vegetables hands"),
  t("pharmacy", "Pharmacy", ["pharmacist", "chemist", "pharmacy", "health shop"], "pharmacy shelves clean bright", "pharmacist counter medicine"),
  t("childcare", "Childcare & creche", ["creche", "childminder", "montessori", "playschool", "preschool", "after school", "nursery"], "bright playroom toys wooden", "children's crayons paper table"),
  t("home-care", "Home care & elder care", ["home care", "carer", "nursing home", "elderly care", "respite"], "cosy living room armchair afternoon light", "holding hands care elderly"),
  t("tattoo-piercing", "Tattoo & piercing", ["tattoo", "piercing", "tattoo artist", "body art"], "tattoo studio interior moody", "tattoo machine close up"),
  t("lash-brow-makeup", "Makeup & lashes", ["makeup artist", "make up", "lash extensions", "brow", "bridal makeup"], "makeup brushes vanity mirror light", "makeup brush palette close up"),
  t("tanning-beauty", "Tanning & aesthetics", ["spray tan", "tanning", "aesthetics", "botox", "skin clinic", "waxing"], "skin care clinic bright minimal", "skincare products marble"),
  /* food & hospitality */
  t("pub-bar", "Pub & bar", ["pub", "bar", "cocktails", "craft beer", "taproom", "gastropub"], "irish pub interior warm", "pint glass beer tap"),
  t("takeaway", "Takeaway & fast food", ["takeaway", "chipper", "pizza", "burgers", "kebab", "fast food", "delivery food"], "pizza fresh wooden board", "burger close up"),
  t("butcher-deli", "Butcher & deli", ["butcher", "deli", "delicatessen", "meat", "charcuterie", "farm shop"], "butcher shop counter fresh meat", "butcher knife cutting board"),
  t("catering", "Catering", ["caterer", "catering", "buffet", "canapes", "private chef", "event catering"], "catering table food platters", "chef plating canapes"),
  t("food-truck", "Food truck & street food", ["food truck", "street food", "coffee van", "mobile catering", "market stall"], "food truck street evening", "street food cooking grill"),
  t("hotel-bnb", "Hotel, B&B & guesthouse", ["hotel", "b&b", "bed and breakfast", "guesthouse", "self catering", "holiday home", "airbnb", "hostel"], "cosy bedroom country house window", "breakfast table cafetiere"),
  t("ice-cream-sweets", "Ice cream & sweets", ["ice cream", "sweets", "chocolate", "chocolatier", "confectionery", "dessert"], "ice cream cones pastel", "chocolate truffles close up"),
  t("brewery-distillery", "Brewery & distillery", ["brewery", "distillery", "craft beer", "whiskey", "gin", "cider", "winery"], "brewery tanks copper", "whiskey barrels casks"),
  /* retail */
  t("gift-shop", "Gift shop", ["gifts", "gift shop", "cards", "homeware", "craft shop", "souvenirs"], "gift shop shelves warm", "wrapping gift ribbon hands"),
  t("jeweller", "Jeweller", ["jewellery", "jeweller", "rings", "engagement ring", "watches", "goldsmith"], "jewellery display shop light", "ring gemstone close up"),
  t("furniture-store", "Furniture store", ["furniture", "sofas", "beds", "mattress", "home furnishings", "showroom"], "furniture showroom living room", "wood grain furniture detail"),
  t("bookshop", "Bookshop", ["books", "bookshop", "bookstore", "stationery", "comics"], "bookshop shelves cosy", "books stack pages close"),
  t("bike-shop", "Bike shop", ["bicycle", "bikes", "cycling", "bike repair", "e-bike"], "bicycle shop workshop", "bike chain gears close up"),
  t("toy-shop", "Toy & baby shop", ["toys", "toy shop", "baby shop", "kids clothes", "games"], "colourful toys wooden shelves", "wooden toys hands play"),
  t("garden-centre", "Garden centre & nursery", ["garden centre", "plants", "nursery", "greenhouse", "plant shop", "horticulture"], "garden centre plants greenhouse", "seedlings pots hands soil"),
  t("hardware-diy", "Hardware & DIY", ["hardware", "diy", "builders merchant", "tools", "timber merchant", "paint shop"], "hardware store tools shelves", "tools workbench close"),
  t("phone-repair", "Phone & computer repair", ["phone repair", "screen repair", "laptop repair", "computer repair", "mobile phone shop", "tech repair"], "electronics repair bench", "smartphone screen repair tools"),
  t("pet-shop", "Pet shop", ["pet shop", "pet supplies", "aquarium", "pet food", "fish"], "pet shop shelves bright", "cat dog toys close"),
  /* professional services */
  t("estate-agent", "Estate agent", ["estate agent", "property", "letting agent", "auctioneer", "property management", "rentals"], "for sale house exterior sunny", "house keys handover door"),
  t("financial-advisor", "Financial advisor & mortgages", ["financial advisor", "mortgage", "pension", "insurance broker", "investment", "financial planning", "insurance"], "modern office desk laptop natural light", "calculator documents desk pen"),
  t("architect-surveyor", "Architect & surveyor", ["architect", "architectural", "surveyor", "planning permission", "drawings", "engineer", "quantity surveyor"], "architect desk drawings model", "architectural model blueprint close"),
  t("recruitment-hr", "Recruitment & HR", ["recruitment", "recruiter", "hr", "staffing", "employment agency", "training"], "modern open plan office bright", "interview handshake desk"),
  t("marketing-agency", "Marketing & design agency", ["marketing", "branding", "graphic design", "seo", "social media", "web design", "advertising", "agency"], "creative studio desk monitors", "sketching layout designer desk"),
  t("it-support", "IT support", ["it support", "managed it", "computer support", "networking", "cyber", "software", "tech"], "server room cables blue", "laptop coding keyboard close"),
  t("tutoring-grinds", "Tutoring & grinds", ["tutor", "grinds", "tuition", "exam prep", "leaving cert", "language classes", "teacher"], "study desk books lamp", "student notes pen close"),
  t("music-lessons", "Music & dance lessons", ["music lessons", "guitar", "piano", "singing", "dance school", "drama", "ballet", "music school"], "piano keys warm room", "guitar strings hands close"),
  t("funeral-director", "Funeral director", ["funeral", "undertaker", "funeral home", "memorial", "cremation"], "quiet chapel flowers soft light", "white flowers candle soft"),
  t("videographer-dj", "Video & entertainment", ["videographer", "video production", "drone", "band", "live music", "photobooth", "entertainment"], "camera on tripod studio", "video camera lens close"),
  t("printing-copy", "Printing & copy shop", ["print shop", "printing", "flyers", "business cards", "large format", "promotional", "merchandise"], "print shop machine colourful", "printed colour swatches"),
  t("commercial-cleaning", "Commercial cleaning & facilities", ["commercial cleaning", "janitorial", "facilities", "office cleaning", "industrial cleaning"], "clean modern office corridor", "mop bucket floor shine"),
  t("church-community", "Church, club & community", ["church", "parish", "community group", "charity", "club", "society", "volunteer", "gaa", "sports club"], "community hall bright", "hands together group table"),
  t("art-gallery-craft", "Art, craft & gallery", ["artist", "art gallery", "pottery", "ceramics", "craft maker", "handmade", "painting"], "art studio easel light", "pottery clay hands wheel"),
  t("farm-agri", "Farm & agriculture", ["farm", "farmer", "agri", "agricultural", "livestock", "organic", "produce"], "irish farm field green morning", "hay bales close farm"),
  t("fishing-marine", "Boats & marine", ["boat", "marine", "fishing", "charter", "boat trips", "sailing", "kayak"], "harbour boats morning", "rope boat cleat close"),
  t("outdoor-activity", "Outdoor & adventure", ["adventure", "surf school", "outdoor activities", "hiking", "tours", "tour guide", "camping", "glamping"], "coastal cliffs walking trail", "hiking boots trail close"),
  t("sports-coaching", "Sports & coaching", ["football", "sports coaching", "golf", "tennis", "martial arts", "swimming lessons", "boxing"], "sports pitch grass sunrise", "tennis balls racket detail"),
];

export const generic = [
  t("generic-office", "General business (office)", [], "modern bright office desk natural light", "notebook laptop coffee desk close"),
  t("generic-workshop", "General trade (workshop)", [], "tidy workshop tools warm light", "hands using tools close up"),
  t("generic-storefront", "General shop (storefront)", [], "small shop front street colourful", "shop counter till close"),
  t("generic-home", "General home & family", [], "bright home interior living room natural light", "hands tea cup table"),
  t("generic-outdoors", "General outdoors", [], "irish countryside road green morning", "leaves dew close up"),
  t("generic-team", "General team & service", [], "empty meeting table chairs bright", "handshake business desk"),
];
