import Stripe from "stripe";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { ADDONS } from "../lib/payment-links";
import type { GeneratedPaymentLink } from "../lib/payment-links.generated";
import { GENERATED_PAYMENT_LINKS as EXISTING } from "../lib/payment-links.generated";

/* ===========================================================================
   One-time (and safe-to-rerun) setup: creates a Stripe Product + Price +
   Payment Link for every entry in lib/payment-links.ts's ADDONS list, then
   overwrites lib/payment-links.generated.ts with the result.

   Run with:  npm run setup:addon-links   (needs STRIPE_SECRET_KEY set)

   Safe to run more than once: if an addon already has a generated Payment
   Link at the currently-expected price, it's left alone. Only missing or
   stale (wrong price) entries are (re)created. Stripe Prices are immutable,
   so "stale price" means a new Price + Payment Link, not an edit.
   =========================================================================== */

const key = process.env.STRIPE_SECRET_KEY;
if (!key) {
  console.error("STRIPE_SECRET_KEY is not set. See .env.example.");
  process.exit(1);
}
const stripe = new Stripe(key);

const OUT_FILE = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
  "lib",
  "payment-links.generated.ts"
);

async function findExistingProduct(addonKey: string): Promise<Stripe.Product | null> {
  // No Search API dependency (that needs a separately-enabled index) — the
  // catalogue is tiny (8 items), so listing and filtering on metadata is
  // simple and reliable.
  for await (const product of stripe.products.list({ limit: 100 })) {
    if (product.metadata?.web99_addon_key === addonKey && product.active) return product;
  }
  return null;
}

async function ensureAddon(addon: (typeof ADDONS)[number]): Promise<GeneratedPaymentLink> {
  const priceCents = Math.round(addon.priceEur * 100);
  const existing = EXISTING[addon.key];

  if (existing) {
    const price = await stripe.prices.retrieve(existing.priceId);
    if (price.active && price.unit_amount === priceCents && price.currency === "eur") {
      console.log(`= ${addon.key} unchanged (€${addon.priceEur})`);
      return existing;
    }
    console.log(`~ ${addon.key} price changed (was ${price.unit_amount}, now ${priceCents}) — creating a new Price + Payment Link`);
  }

  let product = await findExistingProduct(addon.key);
  if (!product) {
    product = await stripe.products.create({
      name: addon.label,
      description: addon.description,
      metadata: { web99_addon_key: addon.key },
    });
    console.log(`+ created product ${product.id} (${addon.label})`);
  }

  const price = await stripe.prices.create({
    product: product.id,
    currency: "eur",
    unit_amount: priceCents,
    metadata: { web99_addon_key: addon.key },
  });

  const paymentLink = await stripe.paymentLinks.create({
    line_items: [{ price: price.id, quantity: 1 }],
    metadata: { web99_addon_key: addon.key },
    after_completion: { type: "hosted_confirmation" },
  });

  console.log(`+ ${addon.key}: €${addon.priceEur} -> ${paymentLink.url}`);

  return {
    productId: product.id,
    priceId: price.id,
    paymentLinkId: paymentLink.id,
    url: paymentLink.url,
  };
}

async function main() {
  const result: Record<string, GeneratedPaymentLink> = {};
  for (const addon of ADDONS) {
    result[addon.key] = await ensureAddon(addon);
  }

  const body = `/* ===========================================================================
   AUTO-GENERATED by scripts/setup-addon-links.ts. Do not hand-edit — rerun
   \`npm run setup:addon-links\` (with STRIPE_SECRET_KEY set) instead, and it
   will overwrite this file with the current Product/Price/Payment Link IDs.

   Payment Link URLs are public — a customer clicks one to pay — so this file
   is safe to commit. Nothing in it is a secret.
   =========================================================================== */

export interface GeneratedPaymentLink {
  productId: string;
  priceId: string;
  paymentLinkId: string;
  url: string;
}

export const GENERATED_PAYMENT_LINKS: Record<string, GeneratedPaymentLink> = ${JSON.stringify(result, null, 2)};
`;

  writeFileSync(OUT_FILE, body);
  console.log(`\nWrote ${Object.keys(result).length} Payment Links to lib/payment-links.generated.ts`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
